### ISSUE TITLE
如何使用第三方的api

### ISSUE THREAD

**Issue by wrhsd1** [vlinx-io/infinite-search#1]
请问大佬 如何使用第三方的api?还是如何设置使用的chat模型

**Comment by vlinx-io** [comment]
第三方API指的是本地LLM，还是Gemini？我们是基于LangChain4J, LangChain4J有提供关于本地LLM的支持，你可以看下LangChain4J的相关教程，Gemini的话，我们回头会推出一个开源的可以兼容LangChain4J的API

**Comment by wrhsd1** [comment]
抱歉没说明白 是第三方转发的openai的api，请求地址指向第三方自定义的endpoint
代替官方的https://api.openai.com/v1/chat/completions

**Comment by vlinx-io** [comment]
这个没有支持，你可以自行修改代码。

**Comment by wrhsd1** [comment]
好的 明白
